language: java
sudo: false
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
    - "react-frontend/node_modules"
env:
  - NODE_VERSION=14
before_install:
  - nvm install $NODE_VERSION
before_script:
  - mkdir -p src/main/resources/static
  - cd react-frontend
  - npm install
  - npm run build
  - cd ..
  - cp -avr react-frontend/build/. src/main/resources/static

notifications:
  email:
    on_success: "never"
    on_failure: "never"
#deploy:
#  - provider: releases
#    api_key: ${GITHUB_OAUTH_TOKEN}
#    file: target/backend-service-${TRAVIS_BRANCH}.0.0-SNAPSHOT.jar
#    skip_cleanup: true
#    on:
#      jdk: openjdk8

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  on:
    tags: true
    file: target/backend-service-${TRAVIS_BRANCH}.0.0-SNAPSHOT.jar
  skip_cleanup: true
#deploy:
#  provider: releases
#  api_key: $GITHUB_OAUTH_TOKEN
#  skip_cleanup: true
#  on:
#    tags: true
#  file: "target/OncopretR-0.0.1-SNAPSHOT.jar"
#deploy:
#  - provider: heroku
#    api_key: $HEROKU_API_KEY
#    app: spring-order-service
#    skip_cleanup: true
#    on:
#      all_branches: true
